version: '3'
services:
  jupyterlab:
    image: jupyterlab-tensors:latest
    ports:
      - "8889:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
